apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: k8s-go-handson-01
spec:
  replicas: 3
  template:
    metadata:
      labels:
        app: k8s-go-handson-01
    spec:
      containers:
        - name: k8s-go-handson-01
          image: "registry.ng.bluemix.net/anlixue/k8s-go-handson-01:v1"
          env:
            - name: WEBAPP_PORT
              value: "8000"
          
          #imagePullPolicy: Never
          #imagePullPolicy: IfNotPresent
          imagePullPolicy: Always
          ports:
            - name: http
              containerPort: 8000
---
apiVersion: v1
kind: Service
metadata:
  name: k8s-go-handson-01
  labels:
    app: k8s-go-handson-01
spec:
  type: NodePort
  selector:
    app: k8s-go-handson-01
  ports:
   - protocol: TCP
     port: 8000
     #nodePort: ${NODEPORT:-31080}
     nodePort: 30180
