apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: redisdb-handson-02
spec:
  replicas: 1
  template:
    metadata:
      labels:
        app: redisdb-handson-02
    spec:
      containers:
        - name: redisdb-handson-02
          image: "redis:3.0.7-alpine"
          imagePullPolicy: IfNotPresent
          #imagePullPolicy: Always
          ports:
            - name: redisport
              containerPort: 6379
---
apiVersion: v1
kind: Service
metadata:
  name: redisdb-handson-02
  labels:
    app: redisdb-handson-02
spec:
  type: NodePort
  selector:
    app: redisdb-handson-02
  ports:
   - protocol: TCP
     port: 6379
---
apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: k8s-go-handson-02
spec:
  replicas: 3
  template:
    metadata:
      labels:
        app: k8s-go-handson-02
    spec:
      containers:
        - name: k8s-go-handson-02
          image: "registry.ng.bluemix.net/anlixue/k8s-go-handson-02:v1"
          env:
            - name: WEBAPP_PORT
              value: "8000"
            - name: REDIS_HOST
              value: "redisdb-handson-02"
          
          #imagePullPolicy: Never
          #imagePullPolicy: IfNotPresent
          imagePullPolicy: Always
          ports:
            - name: http
              containerPort: 8000
---
apiVersion: v1
kind: Service
metadata:
  name: k8s-go-handson-02
  labels:
    app: k8s-go-handson-02
spec:
  type: NodePort
  selector:
    app: k8s-go-handson-02
  ports:
   - protocol: TCP
     port: 8000
     nodePort: 30280

